# Generated by Django 4.1.5 on 2023-02-14 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_delete_member'),
        ('examples', '0007_example_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='annotations_approved_by_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.role'),
        ),
    ]
